store_test = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[2]/a[1]"
stor_product = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[9]/div[1]/a[1]"
store_add_cart = "//button[contains(text(),'Add to cart')]"
store_view_cart = "//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
coupon_code = "//input[@id='coupon_code']"
applyCoupon = "//button[contains(text(),'Apply coupon')]"
#############################################################################################################
test_men = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[3]/a[1] "
men_product = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[1]/div[1]/a[1]"
add_men_product = "//button[contains(text(),'Add to cart')]"
viw_men_product = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/a[1]"
men_coupon = "coupon_code"
apply_men_product = "//button[contains(text(),'Apply coupon')]"
# *************************************************************
test_women = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[4]/a[1]"
women_product = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[5]/div[1]/a[1]"
add_to_cart_women_pro = "//button[contains(text(),'Add to cart')]"
view_women_produ_on_cart = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/a[1]"
women_coupon = "//input[@id='coupon_code']"
apply_women_coupon = "//button[contains(text(),'Apply coupon')]"
# *****************************************************************
test_accessory = "//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[5]/a[1]"
accessory_product = "//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[4]/div[1]/a[1]"
accessory_add_cart = "//button[contains(text(),'Add to cart')]"
view_accessory_product_on_cart = "//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
accessory_coupon = "//input[@id='coupon_code']"
apply_to_buy_accessory_product = "//button[contains(text(),'Apply coupon')]"
